//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Leaves.Models
{
    using System;
    using System.Collections.Generic;

    public partial class WishListIndividual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WishListIndividual()
        {
            this.Donation = new HashSet<Donation>();
        }

        public int Wish_List_ID { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<System.DateTime> List_Submit_Date { get; set; }
        public string Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donation { get; set; }
        public virtual Item Item { get; set; }
        public virtual Refugee Refugee { get; set; }

       
    }
}
