//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Leaves.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DId { get; set; }
        public Nullable<int> Wish_List_Id { get; set; }
        public string Donation_Item { get; set; }
        public Nullable<System.DateTime> Donate_Date { get; set; }
        public string Status { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual Wish_List Wish_List { get; set; }
    }
}
