//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Leaves.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Item_ID { get; set; }
        public Nullable<int> RID { get; set; }
        public string Item_Name { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public byte[] Icon { get; set; }
        public Nullable<decimal> Estimated_Price { get; set; }
        public string Status { get; set; }
    
        public virtual Wish_List Wish_List { get; set; }
    }
}
