//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Leaves.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refugee
    {
        public int RID { get; set; }
        public Nullable<int> AthorityCode { get; set; }
        public string RefugeeFName { get; set; }
        public string RefugeeLName { get; set; }
        public byte[] Icon { get; set; }
        public string Password { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public string Family_Description { get; set; }
    
        public virtual Wish_List Wish_List { get; set; }
    }
}
