//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Leaves.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refugee
    {
        public int RefugeeID { get; set; }
        public string RefugeeFName { get; set; }
        public string RefugeeLName { get; set; }
        public string Phone { get; set; }
    }
}
