//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Leaves.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wish_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wish_List()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int Wish_List_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> RId { get; set; }
        public Nullable<System.DateTime> List_Submit_Date { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual Item Item { get; set; }
        public virtual Refugee Refugee { get; set; }
    }
}
